package com.v2soft.training.model;
// Generated Nov 7, 2019 4:36:33 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "employees")
public class Department implements java.io.Serializable {

	private String deptId;
	private String deptName;
	private Set<Employeeinfo> employeeinfos = new HashSet<Employeeinfo>(0);
	private Securitycredentials securitycredentials;

	public Department() {
	}

	public Department(String deptId, String deptName) {
		this.deptId = deptId;
		this.deptName = deptName;
	}

	public Department(String deptId, String deptName, Set<Employeeinfo> employeeinfos,
			Securitycredentials securitycredentials) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.employeeinfos = employeeinfos;
		this.securitycredentials = securitycredentials;
	}

	@Id

	@Column(name = "deptId", unique = true, nullable = false, length = 10)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "deptName", nullable = false, length = 15)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Employeeinfo> getEmployeeinfos() {
		return this.employeeinfos;
	}

	public void setEmployeeinfos(Set<Employeeinfo> employeeinfos) {
		this.employeeinfos = employeeinfos;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "department")
	public Securitycredentials getSecuritycredentials() {
		return this.securitycredentials;
	}

	public void setSecuritycredentials(Securitycredentials securitycredentials) {
		this.securitycredentials = securitycredentials;
	}

}
