package com.v2soft.training.model;
// Generated Nov 7, 2019 4:36:33 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Salaryinfo generated by hbm2java
 */
@Entity
@Table(name = "salaryinfo", catalog = "employees")
public class Salaryinfo implements java.io.Serializable {

	private String employeeId;
	private Employeeinfo employeeinfo;
	private String basicPay;
	private String hra;
	private String travelAllowance;
	private String medicalAllowance;

	public Salaryinfo() {
	}

	public Salaryinfo(Employeeinfo employeeinfo, String basicPay, String hra, String travelAllowance,
			String medicalAllowance) {
		this.employeeinfo = employeeinfo;
		this.basicPay = basicPay;
		this.hra = hra;
		this.travelAllowance = travelAllowance;
		this.medicalAllowance = medicalAllowance;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "employeeinfo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "employeeId", unique = true, nullable = false, length = 50)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Employeeinfo getEmployeeinfo() {
		return this.employeeinfo;
	}

	public void setEmployeeinfo(Employeeinfo employeeinfo) {
		this.employeeinfo = employeeinfo;
	}

	@Column(name = "basicPay", nullable = false, length = 15)
	public String getBasicPay() {
		return this.basicPay;
	}

	public void setBasicPay(String basicPay) {
		this.basicPay = basicPay;
	}

	@Column(name = "hra", nullable = false, length = 15)
	public String getHra() {
		return this.hra;
	}

	public void setHra(String hra) {
		this.hra = hra;
	}

	@Column(name = "travelAllowance", nullable = false, length = 15)
	public String getTravelAllowance() {
		return this.travelAllowance;
	}

	public void setTravelAllowance(String travelAllowance) {
		this.travelAllowance = travelAllowance;
	}

	@Column(name = "medicalAllowance", nullable = false, length = 15)
	public String getMedicalAllowance() {
		return this.medicalAllowance;
	}

	public void setMedicalAllowance(String medicalAllowance) {
		this.medicalAllowance = medicalAllowance;
	}

}
