//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 12:13:52 AM EST 
//


package localhost._8080.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateEmployeeRequestWithSecurity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateEmployeeRequestWithSecurity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SecurityCredentials" type="{http://localhost:8080/types}SecurityInformation"/>
 *         &lt;element name="EmployeeWithoutSalary" type="{http://localhost:8080/types}EmployeeWithoutSalary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateEmployeeRequestWithSecurity", propOrder = {
    "securityCredentials",
    "employeeWithoutSalary"
})
public class CreateEmployeeRequestWithSecurity {

    @XmlElement(name = "SecurityCredentials", required = true)
    protected SecurityInformation securityCredentials;
    @XmlElement(name = "EmployeeWithoutSalary", required = true)
    protected EmployeeWithoutSalary employeeWithoutSalary;

    /**
     * Gets the value of the securityCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityInformation }
     *     
     */
    public SecurityInformation getSecurityCredentials() {
        return securityCredentials;
    }

    /**
     * Sets the value of the securityCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityInformation }
     *     
     */
    public void setSecurityCredentials(SecurityInformation value) {
        this.securityCredentials = value;
    }

    /**
     * Gets the value of the employeeWithoutSalary property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeWithoutSalary }
     *     
     */
    public EmployeeWithoutSalary getEmployeeWithoutSalary() {
        return employeeWithoutSalary;
    }

    /**
     * Sets the value of the employeeWithoutSalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeWithoutSalary }
     *     
     */
    public void setEmployeeWithoutSalary(EmployeeWithoutSalary value) {
        this.employeeWithoutSalary = value;
    }

}
